### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by equipetecnologia** [pplonski/mail4gpt#1]
I have configured .env as per instructions and run the container using docker-compose

docker:/opt/mail4gpt# docker-compose up -d
[+] Building 0.0s (0/0)
[+] Running 2/2
 ✔ Container mail4gpt-server-1  Started
 ✔ Container mail4gpt-nginx-1   Started

Once trying to open url http://<ip>:80 and got "Bad Request (400)"

There is any other additional config or logs that I can check what is going on ?

Thanks

**Comment by pplonski** [comment]
Are you opening `http://0.0.0.0`? Do you have any error logs from docker in terminal?

**Comment by equipetecnologia** [comment]
yes, opening Docker server http://192.168.1.8:8282/schema
because I exposed external port to 8282 since 80 was in use, but is up and running

/opt/mail4gpt# cat docker-compose.yml
version: '2'

services:
    nginx:
        restart: unless-stopped
        image: nginx:stable-alpine
        ports:
            - 8282:80
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - server
        command: "/bin/sh -c 'nginx -g \"daemon off;\"'"
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        entrypoint: /app/docker/server/entrypoint.sh
        expose:
            - 8000
        environment:
            SECRET_KEY: ${SECRET_KEY}
            EMAIL_ADDRESS: ${EMAIL_ADDRESS}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
            IMAP_ADDRESS: ${IMAP_ADDRESS}
            IMAP_PORT: ${IMAP_PORT}
            SMTP_ADDRESS: ${SMTP_ADDRESS}
            SMTP_PORT: ${SMTP_PORT}



Ngix running: 
024/01/02 12:55:45 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2024/01/02 12:55:45 [notice] 1#1: OS: Linux 5.10.0-9-amd64
2024/01/02 12:55:45 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/01/02 12:55:45 [notice] 1#1: start worker processes
2024/01/02 12:55:45 [notice] 1#1: start worker process 7
2024/01/02 12:55:45 [notice] 1#1: start worker process 8
2024/01/02 12:55:45 [notice] 1#1: start worker process 9
2024/01/02 12:55:45 [notice] 1#1: start worker process 10

and  GPT_server as well:

Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, sessions, sites
Running migrations:
  No migrations to apply.
Your auth token
Token tokens[0].key
[2024-01-02 12:56:05 +0000] [9] [INFO] Starting gunicorn 21.2.0
[2024-01-02 12:56:05 +0000] [9] [INFO] Listening at: http://0.0.0.0:8000 (9)
[2024-01-02 12:56:05 +0000] [9] [INFO] Using worker: gthread
[2024-01-02 12:56:05 +0000] [10] [INFO] Booting worker with pid: 10
[2024-01-02 12:56:05 +0000] [11] [INFO] Booting worker with pid: 11
[2024-01-02 12:56:05 +0000] [12] [INFO] Booting worker with pid: 12
[2024-01-02 12:56:06 +0000] [13] [INFO] Booting worker with pid: 13

**Comment by equipetecnologia** [comment]
Complete log from terminal:

[+] Running 2/0
 ✔ Container mail4gpt-server-1  Running0.0s
 ✔ Container mail4gpt-nginx-1   Running0.0s
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: using the "epoll" event method
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: nginx/1.24.0
mail4gpt-nginx-1   |2024/01/03 03:56:01 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4)
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: OS: Linux 5.10.0-9-amd64
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: start worker processes
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: start worker process 8
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: start worker process 9
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: start worker process 10
mail4gpt-nginx-1   | 2024/01/03 03:56:01 [notice] 1#1: start worker process 11
mail4gpt-server-1  | Operations to perform:
mail4gpt-server-1  |   Apply all migrations: admin, auth, authtoken, contenttypes, sessions, sites
mail4gpt-server-1  | Running migrations:
mail4gpt-server-1  |   Applying contenttypes.0001_initial... OK
mail4gpt-server-1  |   Applying auth.0001_initial... OK
mail4gpt-server-1  |   Applying admin.0001_initial... OK
mail4gpt-server-1  |   Applying admin.0002_logentry_remove_auto_add... OK
mail4gpt-server-1  |   Applying admin.0003_logentry_add_action_flag_choices... OK
mail4gpt-server-1  |   Applying contenttypes.0002_remove_content_type_name... OK
mail4gpt-server-1  |   Applying auth.0002_alter_permission_name_max_length... OK
mail4gpt-server-1  |   Applying auth.0003_alter_user_email_max_length... OK
mail4gpt-server-1  |   Applying auth.0004_alter_user_username_opts... OK
mail4gpt-server-1  |   Applying auth.0005_alter_user_last_login_null... OK
mail4gpt-server-1  |   Applying auth.0006_require_contenttypes_0002... OK
mail4gpt-server-1  |   Applying auth.0007_alter_validators_add_error_messages... OK
mail4gpt-server-1  |   Applying auth.0008_alter_user_username_max_length... OK
mail4gpt-server-1  |   Applying auth.0009_alter_user_last_name_max_length... OK
mail4gpt-server-1  |   Applying auth.0010_alter_group_name_max_length... OK
mail4gpt-server-1  |   Applying auth.0011_update_proxy_permissions... OK
mail4gpt-server-1  |   Applying auth.0012_alter_user_first_name_max_length... OK
mail4gpt-server-1  |   Applying authtoken.0001_initial... OK
mail4gpt-server-1  |   Applying authtoken.0002_auto_20160226_1747... OK
mail4gpt-server-1  |   Applying authtoken.0003_tokenproxy... OK
mail4gpt-server-1  |   Applying sessions.0001_initial... OK
mail4gpt-server-1  |   Applying sites.0001_initial... OK
mail4gpt-server-1  |   Applying sites.0002_alter_domain_unique... OK
mail4gpt-server-1  | Your auth token
mail4gpt-server-1  | Token d7381965d9c7e98d886cafd3025a947d33ec2da2
mail4gpt-server-1  | [2024-01-03 03:56:06 +0000] [9] [INFO] Starting gunicorn 21.2.0
mail4gpt-server-1  | [2024-01-03 03:56:06 +0000] [9] [INFO] Listening at: http://0.0.0.0:8000 (9)
mail4gpt-server-1  | [2024-01-03 03:56:06 +0000] [9] [INFO] Using worker: gthread
mail4gpt-server-1  | [2024-01-03 03:56:06 +0000] [10] [INFO] Booting worker with pid: 10
mail4gpt-server-1  | [2024-01-03 03:56:06 +0000] [11] [INFO] Booting worker with pid: 11
mail4gpt-server-1  | [2024-01-03 03:56:06 +0000] [12] [INFO] Booting worker with pid: 12
mail4gpt-server-1  | [2024-01-03 03:56:07 +0000] [13] [INFO] Booting worker with pid: 13

**Comment by pplonski** [comment]
Have you tried `http://0.0.0.0:8282/schema`

**Comment by equipetecnologia** [comment]
Yes I did, same error: Bad Request (400)

**Comment by equipetecnologia** [comment]
I have found what is happening:

/mail4gpt/backend/backend# cat settings.py |grep -i allow
ALLOWED_HOSTS = ["127.0.0.1", "0.0.0.0", DEPLOY_DOMAIN]

/mail4gpt/backend/backend# cat settings.py |grep -i allow
ALLOWED_HOSTS = ["*"]

I know that's a security issue allowing *, but for tests that resolved my problem. 

Then, i think that you could fix the code using some variable on DEPLOY_DOMAIN. I didn't test, but seems that it should be
$DEPLOY_DOMAIN  or "DEPLOY_DOMAIN" ?

Not sure. just trying to help out.
