### ISSUE TITLE
OS Dependency for mail4gpt

### ISSUE THREAD

**Issue by vbrah8854** [pplonski/mail4gpt#2]
I was going through ReadMe , before starting to deploy 
Is this Solution works in Windows based OS

**Comment by pplonski** [comment]
If you can run docker compose on Windows then it should work. I didn't test on Windows machine. I was running it on Ubuntu.

**Comment by vbrah8854** [comment]
Hi , Thanks

I am able to deploy it in Ubuntu I will try in Windows later

Before that I have few queries in deployment 

docker-compose up  is only enough to start the server?

or we need to bring server up by init-letsencrypt.sh script?

Also SECRET_KEY  in settings.py can the default key in the .py be used for local host test or do I need to generate a new key?

**Comment by pplonski** [comment]
- `init-letsencrypt.sh` is only needed to generate domain keys
- `docker-compose up` is enough to start a server, you can additionally add `-d` to start in the background
- you can leave `SECRET_KEY` as it is, but it is safer to generate a new one
